project:
  type: website
  #render:
  #   - "*.ipynb"
  #   - "!FullReport_MSWord.ipynb"
  preview:
    port: 3210
    browser: false
  output-dir: ../docs
  resources:
    - link-target.js  # This ensures it gets copied to output

website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/Logo_McMaster_and_Ouranos_vertical_trans.png"
    style: "docked" #"floating"
    collapse-level: 1
    #search: true
    contents:
      - Introduction.ipynb
      # - section: "Literature Review" # was: Climate Change Impacts on Electricity Systems
      #   contents:
      #     - section: "Generation"
      #       contents:
      #     - section: "Transmission and distribution"
      #       contents:
      #     - literature_review/demand.ipynb
      - section: "Electricity Sector Activities"
        href: sectors/electricity_sector_activities.ipynb
        contents:
          - section: "Electricity System Planning"
            href: sectors/planning/grid_planning.ipynb
            contents:
              - sectors/planning/demand_forecasting.ipynb
              - sectors/planning/generation_forecasting.ipynb
              - sectors/planning/capacity_expansion_modelling.ipynb
              - sectors/planning/resource_adequacy_planning.ipynb
          - section: "Operations Planning"
            href: sectors/operations/operations_planning.ipynb
            contents:
              - sectors/operations/electrical_system_operations.ipynb
              - sectors/operations/outage_scheduling.ipynb
              - sectors/operations/vegetation_management.ipynb
              - sectors/operations/worker_safety.ipynb    
          - section: "Infrastructure Planning and Asset Management"
            href: sectors/infrastructure/infrastructure_planning.ipynb
            contents:
              - sectors/infrastructure/construction.ipynb
              - sectors/infrastructure/dam_safety_review.ipynb
              - sectors/infrastructure/nuclear_safety_review.ipynb
              - sectors/infrastructure/infrastructure_condition_assessment_and_investment_prioritization.ipynb
              - sectors/infrastructure/infrastructure_design.ipynb
              - sectors/infrastructure/support_supply_chain_decision-making.ipynb
              - sectors/infrastructure/licensing_and_impact-environmental_assessments.ipynb
          - section: "Assurance, Reporting and Disclosures"
            href: sectors/reporting/reporting_disclosure.ipynb
            contents:  
              - sectors/reporting/enterprise_risk_management.ipynb
              - sectors/reporting/esg_and_sustainability_reporting.ipynb
      # The section on climate datasets
      - section: "Climate Datasets"
        href: datasets/Climate_Datasets_Overview.ipynb
        contents:
          - datasets/Dataset_Template.ipynb
          - section: "Observational Data"
            href: datasets/observed_data/Observational_Datasets.ipynb
            contents:
              - datasets/observed_data/AHCCD_Station_Data.ipynb
              - datasets/observed_data/NRCanMET_Gridded_Data.ipynb
          - section: "Reanalysis Data"
            href: datasets/reanalysis_data/Reanalysis_Datasets.ipynb
            contents:
              - datasets/reanalysis_data/CaSR.ipynb
              - datasets/reanalysis_data/ERA5-Land.ipynb
              - ERA5
          - section: "Climate Projection Data"
            href: datasets/climate_projection_data/Climate_Projection_Datasets.ipynb
            contents:
              - datasets/climate_projection_data/ESPO-G6_Dataset.ipynb
              - CanDCS-M6
              - CMIP6
              - CORDEX
              - CanLEADv1
              - NEX-GDDP (NASA)
          - section: "Analysis Support Tools"
            href: datasets/tools/Analysis_Support_Tools.ipynb
            contents:
      - section: Workshops
        href: workshops/intro_workshops.ipynb
        contents:
          - workshops/content_particip.ipynb
          - workshops/findings.ipynb      
      - dmdu/DMDU.ipynb        

format:
  html:
    output-dir: ../html
    theme: flatly
    css: styles/styles.css
    toc: true
    toc-title: Content
    toc-expand: 0
    code-fold: true
    csl: styles/nature.csl
    # csl: styles/elsevier-harvard.csl
    # citation-style: numeric
    # cite-method: biblatex
    # biblatexoptions:
    #   - citestyle = authoryear
    include-after-body: link-target.js
    embed-resources: true
    allow-raw-html: true

bibliography:
  - literature_review/references.bib
  - datasets/references.bib
  - sectors/references.bib







