project:
  type: website
  output-dir: ../html
  bibliography: references.bib


website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/Logo_McMaster_and_Ouranos.png"
    style: "docked" #"floating"
    collapse-level: 1
    #search: true
    contents:
      - text: "Introduction"
        href: Introduction.ipynb
      - section: "Electricity Sector Activities"
        href: sectors/electricity_sector_activities.ipynb
        contents:
          - section: "Climat change impacts on electricity systems"
            contents:
              - section: "Generation"
                contents:
                  - sectors/construction.ipynb
                  - sectors/infrastructure_design.ipynb
              - section: "Transmission and distribution"
                contents:
                  - sectors/construction.ipynb
                  - sectors/infrastructure_design.ipynb
                  - sectors/vegetation_management.ipynb
              - section: "Demand"
                contents:
                  - sectors/demand_forecasting.ipynb
          - section: "Integration of climate data in electricity system planning"
            contents:
              - section: "Forecasting with climate data"
                contents:
                  - sectors/electrical_system_operations.ipynb
                  - sectors/generation_forecasting.ipynb
                  - sectors/infrastructure_condition_assessment_and_investment_prioritization.ipynb
                  - sectors/outage_scheduling.ipynb
                  - sectors/resource_adequacy_planning.ipynb
                  - sectors/forest_fire_monitoring_and_awareness.ipynb
              - section: "Tools and models"
                contents:
                  - sectors/capacity_expansion_modelling.ipynb
                  - sectors/dam_safety_review.ipynb
                  - sectors/nuclear_safety_review.ipynb
              - section: "Uncertainty management"
                contents:
              - sectors/esg_and_sustainability_reporting.ipynb
              - sectors/licensing_and_impact-environmental_assessments.ipynb
              - sectors/proactive_management_of_heavily_loaded_assets.ipynb
              - sectors/support_supply_chain_decision-making.ipynb
              - sectors/worker_safety.ipynb
          
# The section on climate datasets
      - section: "Climate Datasets"
        href: datasets/Climate_Dataset_Overview.ipynb
        contents:
          - section: "Reanalysis data"
            href: datasets/temperature/Temperature_Datasets.ipynb
            contents:
              - datasets/temperature/ERA5-Land.ipynb
              - datasets/temperature/RDRS.ipynb
          - section: "Station data"
            href: datasets/precipitation/Precipitation_Datasets.ipynb
            contents:
              - datasets/temperature/RDRS.ipynb # @ToDo: This is not precip yet!
          - section: "Climate projection data"
            href: datasets/wind/Wind_Datasets.ipynb
            contents:
            - datasets/wind/RDRS.ipynb # @ToDo: This is not precip yet!
          - section: "Analysis Support Tools"
            href: datasets/tools/Analysis_Support_Tools.ipynb
            contents:
            - datasets/tools/Point_Location_Compare.ipynb # @ToDo: This is not precip yet!

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: Content
    toc-expand: 0
    code-fold: true



