project:
  type: website
  output-dir: ../html

website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/Logo_McMaster_and_Ouranos.png"
    style: "docked" #"floating"
    collapse-level: 1
    #search: true
    contents:
      - Introduction.ipynb
      - section: "Climat change impacts on electricity systems"
        contents:
        - section: "Generation"
          contents:
        - section: "Transmission and distribution"
          contents:
        - literature_review/demand.ipynb
      #     - section: "Integration of climate data in electricity system planning"
      #       contents:
      #         - section: "Forecasting with climate data"
      #           contents:
      #         - section: "Tools and models"
      #           contents:
      #         - section: "Uncertainty management"
      #           contents:
      - section: "Electricity Sector Activities"
        href: sectors/electricity_sector_activities.ipynb
        contents:
          - sectors/capacity_expansion_modelling.ipynb
          - sectors/construction.ipynb
          - sectors/dam_safety_review.ipynb
          - sectors/demand_forecasting.ipynb
          - sectors/electrical_system_operations.ipynb
          - sectors/enterprise_risk_management.ipynb
          - sectors/esg_and_sustainability_reporting.ipynb
          - sectors/forest_fire_monitoring_and_awareness.ipynb
          - sectors/generation_forecasting.ipynb
          - sectors/infrastructure_condition_assessment_and_investment_prioritization.ipynb
          - sectors/infrastructure_design.ipynb
          - sectors/infrastructure_design.ipynb
          - sectors/licensing_and_impact-environmental_assessments.ipynb
          - sectors/nuclear_safety_review.ipynb
          - sectors/outage_scheduling.ipynb
          - sectors/proactive_management_of_heavily_loaded_assets.ipynb
          - sectors/resource_adequacy_planning.ipynb
          - sectors/support_supply_chain_decision-making.ipynb
          - sectors/vegetation_management.ipynb
          - sectors/worker_safety.ipynb          
# The section on climate datasets
      - section: "Climate Datasets"
        href: datasets/Climate_Dataset_Overview.ipynb
        contents:
          - section: "Observational Data"
            href: datasets/observed_data/Observational_Datasets.ipynb
            contents:
              - datasets/observed_data/AHCCD_Station_Data.ipynb
              - datasets/observed_data/NRCanMET_Gridded_Data.ipynb
          - section: "Reanalysis Data"
            href: datasets/reanalysis_data/Reanalysis_Datasets.ipynb
            contents:
              - datasets/reanalysis_data/ERA5-Land.ipynb
              - datasets/reanalysis_data/CaSR.ipynb
          - section: "Climate Projection Data"
            href: datasets/climate_projection_data/Climate_Projection_Datasets.ipynb
            contents:
              - datasets/climate_projection_data/ESPO-G6_Dataset.ipynb
          - section: "Analysis Support Tools"
            href: datasets/tools/Analysis_Support_Tools.ipynb
            contents:
              - datasets/tools/Point_Location_Compare.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: Content
    toc-expand: 0
    code-fold: true
    include-after-body: link-target.js

bibliography:
  - reference.bib






