project:
  type: website

website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/ouranos_logo_vertical_couleur_petit.png"
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: Introduction.ipynb
      - section: "Electricity Sector Activities"
        href: sectors/electricity_sector_activities.ipynb
        contents:
          - sectors/capacity_expansion_modelling.ipynb
          - sectors/construction.ipynb
          - sectors/dam_safety_review.ipynb
          - sectors/demand_forecasting.ipynb
          - sectors/electrical_system_operations.ipynb
          - sectors/enterprise_risk_management.ipynb
          - sectors/esg_and_sustainability_reporting.ipynb
          - sectors/forest_fire_monitoring_and_awareness.ipynb
          - sectors/generation_forecasting.ipynb
          - sectors/infrastructure_condition_assessment_and_investment_prioritization.ipynb
          - sectors/infrastructure_design.ipynb
          - sectors/innovation_investments.ipynb
          - sectors/licensing_and_impact-environmental_assessments.ipynb
          - sectors/nuclear_safety_review.ipynb
          - sectors/outage_scheduling.ipynb
          - sectors/proactive_management_of_heavily_loaded_assets.ipynb
          - sectors/resource_adequacy_planning.ipynb
          - sectors/support_supply_chain_decision-making.ipynb
          - sectors/vegetation_management.ipynb
          - sectors/worker_safety.ipynb
          
# The section on climate datasets
      - section: "Climate Datasets"
        href: datasets/Climate_Dataset_Summary.ipynb
        contents:
          - section: "Temperature"
            href: datasets/temperature/Temperature_Datasets.ipynb
            contents:
              - datasets/temperature/RDRS.ipynb
          - section: "Precipitation"
            href: datasets/precipitation/Precipitation_Datasets.ipynb
            contents:
              - datasets/temperature/RDRS.ipynb # @ToDo: This is not precip yet!
          - section: "Wind"
            href: datasets/wind/Wind_Datasets.ipynb
            contents:
            - datasets/wind/RDRS.ipynb # @ToDo: This is not precip yet!

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



