project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!development/deprecated/IPCC_information.ipynb"
    - "!development/deprecated/electricity_sector_activities_old.ipynb"
    - "!development/legacy/Guidance_Overview.qmd"
    - "!development/legacy/core_concepts.qmd"
    - "!development/drafts/TextSectionParkingLot.ipynb"
    - "!development/tools/NRCanMET_check.ipynb"
    - "!datasets/observed_data/CanGrid.qmd"
    - "!sectors/planning/infrastructure_condition_assessment_and_investment_prioritization.ipynb"
    - "!sectors/operations/proactive_management_of_heavily_loaded_assets.ipynb"
  preview:
    port: 3210
    browser: false
  output-dir: ../docs
  resources:
    - link-target.js  # This ensures it gets copied to output
    - auto-open-callout.js
    - organizational_capability/*.xlsx
    - apply_climate_data/Indigenous_Knowledge_Guidance.pdf

website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/Logo_McMaster_and_Ouranos_vertical_trans.png"
    style: "docked" #"floating"
    collapse-level: 1
    #search: true
    contents:
      - text: "Start Here"
        href: PurposeOfTheGuide.qmd
      - section: "Electricity-Sector Activities"
        href: sectors/electricity_sector_activities.qmd
        contents:
          - section: "Electricity-System Planning"
            contents:
              - text: "Demand Forecasting"
                href: sectors/planning/demand.qmd
              - text: "Generation Forecasting"
                href: sectors/planning/generation_forecasting.qmd
              - text: "Capacity Expansion Modelling"
                href: sectors/planning/capacity_expansion_modelling.qmd
              - text: "Resource Adequacy Planning"
                href: sectors/planning/resource_adequacy_planning.qmd
          - section: "Operations Planning"
            contents:
              - text: "Outage Scheduling"
                href: sectors/operations/outage_scheduling.qmd
              - text: "Vegetation Management"
                href: sectors/operations/vegetation_management.qmd
          - section: "Infrastructure Planning and Asset Management"
            contents:
              - text: "Dam Safety Review"
                href: sectors/infrastructure/dam_safety_review.qmd
              - text: "Infrastructure Condition Assessment and Investment Prioritization"
                href: sectors/infrastructure/infrastructure_condition_assessment_and_investment_prioritization.ipynb
              - text: "Infrastructure Design"
                href: sectors/infrastructure/infrastructure_design.ipynb
          - text: "Reporting and Disclosure"
            href: sectors/reporting/reporting_disclosure.qmd
      - section: "Understand Climate Data"
        href: climate_data_fundamentals/Climate_Datasets_Overview.qmd
        contents:
          - text: "Forecasts, Projections and Predictability"
            href: climate_data_fundamentals/Temporal_Horizons_Predictability.qmd
          - text: "Emissions Scenarios"
            href: climate_data_fundamentals/Emissions_scenarios.qmd
          - text: "Climate Model Ensembles"
            href: climate_data_fundamentals/Ensembles.qmd
          - text: "Projection Periods and Global Warming Levels"
            href: climate_data_fundamentals/Time_horizons_GWL.qmd
          - text: "Downscaling and Bias Adjustment"
            href: climate_data_fundamentals/Bias_adjustment.qmd
          - text: "Uncertainty and Confidence"
            href: climate_data_fundamentals/Uncertainty_Confidence.qmd
          - text: "Climate-Information Gaps and Limitations"
            href: climate_data_fundamentals/gaps_data.qmd
          - text: "Climate-Data Formats"
            href: climate_data_fundamentals/Data_Formats.qmd
      - section: "Find and Compare Climate Datasets"
        href: datasets/Climate_Data_Decision_Tree.qmd
        contents:
          - text: "Compare Documented Datasets"
            href: datasets/Datasets_Overview_Table.qmd
          - text: "Find Datasets by Variable"
            href: datasets/Datasets_by_Variable.qmd
          - section: "Observational Data"
            href: datasets/observed_data/Observational_Datasets.ipynb
            contents:
              - text: "AHCCD and CanHom Station Data"
                href: datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb
              - text: "NRCanMet Gridded Data"
                href: datasets/observed_data/NRCANmet_Gridded_Data.ipynb
          - section: "Reanalysis Data"
            href: datasets/reanalysis_data/Reanalysis_Datasets.ipynb
            contents:
              - text: "ERA5-Land"
                href: datasets/reanalysis_data/ERA5-Land.ipynb
              - text: "Canadian Surface Reanalysis (CaSR)"
                href: datasets/reanalysis_data/CaSR.ipynb
          - section: "Climate-Projection Data"
            href: datasets/climate_projection_data/Climate_Projection_Datasets.qmd
            contents:
              - text: CMIP6
                href: datasets/climate_projection_data/CMIP6.ipynb
              - text: CORDEX
                href: datasets/climate_projection_data/CORDEX.ipynb
              - datasets/climate_projection_data/ESPO-G6.ipynb
              - datasets/climate_projection_data/CanDCS-M6.ipynb
              - datasets/climate_projection_data/CanLEAD.ipynb
              - datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb
      - section: "Apply Climate Data"
        href: apply_climate_data/Adaptation.qmd
        contents:
          - text: "Adaptation, Risk and Vulnerability: Core Concepts"
            href: apply_climate_data/core_concepts_adapt.qmd
          - text: "Integrating Climate Information into Models and Decisions"
            href: apply_climate_data/model_integration.qmd
          - text: "Indigenous Knowledge and Climate-Related Decisions"
            href: apply_climate_data/traditional_knowledge.qmd
          - text: "IPCC Information for Electricity-Sector Applications"
            href: apply_climate_data/IPCC_information.qmd
          - section: "Climate Vulnerability and Risk Assessment"
            href: apply_climate_data/risk_assessment.qmd
            contents:
              - text: "Step 1: Establish the Scope and Context"
                href: apply_climate_data/risk_step1.qmd
              - text: "Step 2: Understand the System, Structure, and Components"
                href: apply_climate_data/risk_step2_system.qmd
              - text: "Step 3: Hazard and Exposure Assessment"
                href: apply_climate_data/risk_step3_hazard.qmd
              - text: "Step 4: Climate Vulnerability Assessment"
                href: apply_climate_data/risk_step4_vulnerability.qmd
              - text: "Step 5: Climate Risk Assessment"
                href: apply_climate_data/risk_step5_risk.qmd
              - text: "Step 6: Adaptation Plan"
                href: apply_climate_data/risk_step6_adapt.qmd
              - text: "Step 7: Reporting or Institutionalizing the Decision"
                href: apply_climate_data/risk_step7_institute.qmd
      - section: "Build Organizational Capability"
        #href: maturity_matrix/Maturity_Matrix.qmd
        contents:
          - text: "Organizational Maturity Self-Assessment"
            href: organizational_capability/Maturity_Matrix.qmd
          - text: "Organizational Gaps and Barriers"
            href: organizational_capability/gaps_organization.qmd
          - text: "Procuring Physical Climate-Risk Assessments"
            href: organizational_capability/Guidance_Harrington.qmd
      - section: "Resources and Examples"
        #href: guidance/Climate_Information_Ressources.qmd
        contents:
          - text: "Online Climate-Information Resources"
            href: resources/Climate_Information_Ressources.qmd
          - text: "Example Applications"
            href: resources/Example_Applications.ipynb
          - section: "Analysis Support Tools"
            href: resources/tools/Analysis_Support_Tools.ipynb
            contents:
              - text: "Compare Observational Datasets at a Point"
                href: resources/tools/Point_Location_Compare.ipynb
      - section: Workshops
        href: workshops/intro_workshops.ipynb
        contents:
          - workshops/content_particip.ipynb
          - workshops/findings.ipynb
      - section: "Development Resources"
        contents:
          - text: "Sector Page Template"
            href: development/templates/Sectors_Template.qmd
          - text: "Dataset Page Template"
            href: development/templates/Dataset_Template.ipynb
          - text: "Deprecated Climate Data Fundamentals"
            href: development/deprecated/Deprecated_Climate_Data_Fundamentals.ipynb
          - text: "Quarto Functionality Examples"
            href: development/examples/QuartoFunctionalityExamples.ipynb
      
format:
  html:
    # output-dir: ../html
    theme: 
      - flatly #simplex #united #superhero #zephyr #spacelab #morph #flatly
      - styles/custom.scss
    #linkcolor: "#070BAB" # "#052946" # Ouranos blue
    css: styles/styles.css
    toc: true
    toc-title: Content
    toc-expand: 0
    toc-depth: 4
    code-fold: true
    smooth-scroll: true
    #csl: styles/nature.csl # only superscript numbers in the text
    #csl: styles/elsevier-harvard.csl # Author (year) in the text
    #csl: styles/harvard-cite-them-right-no-et-al.csl # Author (year) in the text
    csl: styles/cambridge-university-press-author-date.csl
    #csl: styles/lancaster-university-harvard.csl
    # citation-style: numeric
    # cite-method: biblatex
    # biblatexoptions:
    #   - citestyle = authoryear
    include-after-body:
      - link-target.js
      # - auto-open-callout.js
      - text: |
          <script src="auto-open-callout.js"></script>
    embed-resources: true
    allow-raw-html: true

bibliography:
  - datasets/references.bib
  - apply_climate_data/adaptation.bib
  - apply_climate_data/guidance.bib
  - organizational_capability/organizational_capability.bib
  - sectors/references.bib
  - sectors/infrastructure/references_dam_safety.bib
  - sectors/planning/references.bib
  - sectors/planning/generation_forecasting.bib
  - sectors/planning/resource_adequacy_planning.bib
  - sectors/planning/capacity_expansion_modelling.bib
  - sectors/reporting/reporting_references.bib
  
