project:
  type: website
  preview:
    port: 3210
    browser: false
  output-dir: ../docs
  resources:
    - link-target.js  # This ensures it gets copied to output
    - auto-open-callout.js
    - maturity_matrix/*.xlsx

website:
  title: "Climate Data for the Electricity Sector"
  page-navigation: true
  navbar: false
  sidebar:
    #title: "Climate Data for the Electricity Sector"  # Adding the title here
    logo: "image/Logo_McMaster_and_Ouranos_vertical_trans.png"
    style: "docked" #"floating"
    collapse-level: 1
    #search: true
    contents:
      - PurposeOfTheGuide.qmd
      - QuartoFunctionalityExamples.ipynb
      - section: "Electricity Sector Activities"
        href: sectors/electricity_sector_activities.ipynb
        contents:
          - sectors/Sectors_Template.qmd
          - section: "Electricity System Planning"
            contents:
              - sectors/planning/demand.qmd
              - sectors/planning/generation_forecasting.qmd
              - sectors/planning/capacity_expansion_modelling.qmd
              - sectors/planning/resource_adequacy_planning.qmd
          - section: "Operations Planning"
            contents:
              - sectors/operations/outage_scheduling.qmd
              - sectors/operations/vegetation_management.qmd
          - section: "Infrastructure Planning and Asset Management"
            contents:
              - sectors/infrastructure/dam_safety_review.qmd
              - sectors/infrastructure/infrastructure_condition_assessment_and_investment_prioritization.ipynb
              - sectors/infrastructure/infrastructure_design.ipynb
          # - section: "Assurance, Reporting and Disclosures"
          - sectors/reporting/reporting_disclosure.qmd
          #   contents:  
          # - sectors/reporting/esg_and_sustainability_reporting.ipynb
      # The page for the maturity matrix
      - maturity_matrix/Maturity_Matrix.qmd
      - section: "Climate Data Fundamentals"
        href: climate_data_fundamentals/Climate_Data_Fundamentals.qmd
        contents:
          - climate_data_fundamentals/Deprecated_Climate_Data_Fundamentals.ipynb
          - climate_data_fundamentals/Temporal_Horizons_Predictability.qmd
          - climate_data_fundamentals/Data_Formats.qmd
      # The section on climate datasets
      - section: "Climate Datasets"
        href: datasets/Climate_Datasets_Overview.ipynb
        contents:
          - datasets/Dataset_Template.ipynb          
          - section: "Observational Data"
            href: datasets/observed_data/Observational_Datasets.ipynb
            contents:
              - datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb
              - datasets/observed_data/NRCANmet_Gridded_Data.ipynb
          - section: "Reanalysis Data"
            href: datasets/reanalysis_data/Reanalysis_Datasets.ipynb
            contents:
              - datasets/reanalysis_data/ERA5-Land.ipynb
              - datasets/reanalysis_data/CaSR.ipynb
          - section: "Climate Projection Data"
            href: datasets/climate_projection_data/Climate_Projection_Datasets.qmd
            contents:
              - text: CMIP6
                href: datasets/climate_projection_data/CMIP6.ipynb
              - text: CORDEX
                href: datasets/climate_projection_data/CORDEX.ipynb
              - datasets/climate_projection_data/ESPO-G6.ipynb
              - datasets/climate_projection_data/CanDCS-M6.ipynb
              - datasets/climate_projection_data/CanLEAD.ipynb
              - datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb
          - datasets/Datasets_by_Variable.qmd
      - section: "Guidance"
        contents:
          - guidance/Climate_Data_Decision_Tree.qmd   
          - guidance/traditional_knowledge.qmd
          - guidance/Climate_Information_Ressources.qmd
          - guidance/Example_Applications.ipynb
          - section: "Analysis Support Tools"
            href: guidance/tools/Analysis_Support_Tools.ipynb
            contents:
              - guidance/tools/Point_Location_Compare.ipynb
      - section: "Gaps and Barriers"
        contents:
          - gaps/gaps_data.qmd 
          - gaps/gaps_organization.qmd  
      - section: Workshops
        href: workshops/intro_workshops.ipynb
        contents:
          - workshops/content_particip.ipynb
          - workshops/findings.ipynb      
      - section: Adaptation
        href: adaptation/Adaptation.qmd
        contents:
          - section: "Core Concepts"
            href: adaptation/core_concepts.qmd
            contents:
              - adaptation/core_concepts_data.qmd
              - adaptation/core_concepts_adapt.qmd
          - adaptation/model_integration.qmd
          - section: "Vulnerability & Risk"
            href: adaptation/risk_assessment.qmd
            contents: 
              - adaptation/risk_assessment.qmd
              - risk_step1.qmd
              - risk_step2_system.qmd
              - risk_step3_hazard.qmd
              - risk_step4_vulnerability.qmd
              - risk_step5_risk.qmd
              - risk_step6_adapt.qmd
              - risk_step7_institute.qmd
               

format:
  html:
    output-dir: ../html
    theme: 
      - flatly #simplex #united #superhero #zephyr #spacelab #morph #flatly
      - styles/custom.scss
    #linkcolor: "#070BAB" # "#052946" # Ouranos blue
    css: styles/styles.css
    toc: true
    toc-title: Content
    toc-expand: 0
    toc-depth: 4
    code-fold: true
    smooth-scroll: true
    #csl: styles/nature.csl # only superscript numbers in the text
    #csl: styles/elsevier-harvard.csl # Author (year) in the text
    #csl: styles/harvard-cite-them-right-no-et-al.csl # Author (year) in the text
    csl: styles/cambridge-university-press-author-date.csl
    #csl: styles/lancaster-university-harvard.csl
    # citation-style: numeric
    # cite-method: biblatex
    # biblatexoptions:
    #   - citestyle = authoryear
    include-after-body:
      - link-target.js
      # - auto-open-callout.js
      - text: |
          <script src="auto-open-callout.js"></script>
    embed-resources: true
    allow-raw-html: true

bibliography:
  - datasets/references.bib
  - sectors/references.bib
  - sectors/infrastructure/references_dam_safety.bib
  - sectors/planning/references.bib
  - sectors/planning/generation_forecasting.bib
  - sectors/planning/resource_adequacy_planning.bib
  - sectors/planning/capacity_expansion_modelling.bib
  - sectors/reporting/reporting_references.bib
  






