---
title: Datasets by Variable

---

The table below helps to find the datasets that provide a specific variable.

| Variable            | Datasets providing this variable |
| -- | --- |
| Temperature         | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Precipitation       | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Snow                | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Wind (speed, components, gusts)                 | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Humidity (RH, specific humidity)                | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Radiation (shortwave, longwave, surface fluxes) | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb) |
| Surface pressure                                | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb) |
| Cloud cover                                     | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Evaporation / Evapotranspiration                | [**Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb) |
| Soil moisture                                   | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb) |
