---
title: IPCC Information at a Glance
jupyter: python3
---


The Intergovernmental Panel on Climate Change (IPCC) is the United Nations body responsible for assessing scientific knowledge related to climate change. Its assessment reports synthesize evidence from peer-reviewed literature and other credible sources to describe the state of climate science, its implications, and options for mitigation and adaptation. These reports draw extensively on climate-model simulations coordinated through initiatives such as the Coupled Model Intercomparison Project (CMIP).

## Summary of confidence in direction of projected change in hazard in North America

The latest IPCC report assesses the evidence for projected changes in a wide range of climatic impact-drivers. This evidence is summarized in Working Group I Table 12.8 [@IPCC_2021_WGI_Ch12]. The table presented here is adapted from that assessment. It summarizes projected changes in key climatic impact-drivers across North America under mid-century warming conditions (approximately 2°C to 2.4°C of global warming). It combines information on the direction of projected change, the confidence in those projections, and the expected emergence of the climate signal relative to natural variability.

![Summary of the confidence in the direction of projected changes in climatic impact-drivers across North America, representing their aggregate characteristic changes by mid-century under RCP4.5 and SSP2-4.5, or higher scenarios, within each AR6 region. These scenarios approximately correspond to global warming levels between 2°C and 2.4°C. The table also includes the assessed observed or projected time of emergence of the climate impact-driver signal from natural interannual variability, where available with at least medium confidence. </br>*Adapted from Working Group I Table 12.8 in* @IPCC_2021_WGI_Ch12.](image/Table12-8_withmap.png)

<div style="font-size: 0.75em;">

1. Snow may increase in some high elevations and during the cold season and decrease in other seasons and at lower elevations.
2. Along sandy coasts and in the absence of additional sediment sinks/sources or any physical barriers to shoreline retreat.
3. Increasing in northern regions and decreasing towards the south.
4. Decreasing in northern regions and increasing towards the south.
5. Higher confidence in northern regions and lower towards the south.
6. Higher confidence in southern regions and lower towards the north.
7. Higher confidence in increase for some climatic impact-driver indices during summer.
8. Increase in convective conditions but decrease in winter extratropical cyclones.

</div>

## References

::: {#refs}
:::