---
title: Find Datasets by Variable

---

The table below helps to find the datasets documented in this guide that provide a specific variable.

| Variable            | Datasets providing this variable |
| ------------------- | --- |
| Temperature         | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Precipitation       | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb), [NRCANmet](../datasets/observed_data/NRCANmet_Gridded_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [ESPO-G6](../datasets/climate_projection_data/ESPO-G6.ipynb), [CanDCS-M6](../datasets/climate_projection_data/CanDCS-M6.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Snow                | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb)|
| Wind                | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Humidity            | **Observational Data:** -</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb)|
| Radiation           | **Observational Data:** N/A</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb), [NEX-GDDP-CMIP6](../datasets/climate_projection_data/NEX-GDDP-CMIP6.ipynb) |
| Surface pressure    | **Observational Data:** [AHCCD / CanHom](../datasets/observed_data/AHCCD-CanHom_Station_Data.ipynb)</br>**Reanalysis Data:** [ERA5-Land](../datasets/reanalysis_data/ERA5-Land.ipynb), [CaSR](../datasets/reanalysis_data/CaSR.ipynb)</br>**Climate Projection Data:** [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), [CORDEX](../datasets/climate_projection_data/CORDEX.ipynb), [CanLEAD](../datasets/climate_projection_data/CanLEAD.ipynb) |

Other variables such as evapotranspiration, soil moisture or cloud cover are often available from modeled datasets, such as [reanalysis](../datasets/reanalysis_data/Reanalysis_Datasets.ipynb) and [climate projection data](../datasets/climate_projection_data/Climate_Projection_Datasets.qmd). Please refer to the respective documentation for more information.
