---
title: "Additional concepts"
bibliography: ../adaptation/adaptation.bib 
---


### [Sections to be distributed somewhere else?]{.red-text}

## Climate Models

Climate models are computer simulations of the Earth system used to understand and project how climate responds to changes in energy balance and composition of the atmosphere. Climate models simulate the response of climate scenarios. That is, climate models are the tools that translate climate scenario pathways into projected climate conditions (warming patterns, rainfall changes, extremes, sea ice decline, etc.). For any given climate model climate projections may vary due to structural differences in the model, climate variability, or different initial conditions between simulations. As such, it is important to use climate projection data that utilize multi-model ensembles for climate assessments, since the ensemble ranges characterize the uncertainty or variation of the possible climate futures within a climate scenario.

### Delta Method

The delta change method is a simple approach used in climate change impact and adaptation studies to translate projected changes from climate models onto observed historical data. It consists of calculating the difference (or ratio) between a future and historical period in a climate model simulation, then applying this “delta” to an observed time series to create a modified dataset representing future conditions. The method preserves the temporal structure and realism of observations while incorporating the modelled climate change signal, making it easy to apply without more complex [bias adjustment](./Bias_adjustment.qmd). Its advantages include simplicity, transparency, and low data requirements. However, similarly to statistical downscaling, it assumes that model biases are stationary. and that changes in variability or extremes are adequately represented by mean shifts or scaling, which may not hold for all variables. Temperature values are usually adjusted with an additive delta while multiplicative factors are used for precipitation to avoid negative values.




