---
title: Ensembles
---

Over 50 major research institutions around the world run global climate models to generate simulations of past climate and projections of future climate conditions. In the context of [Model Intercomparison Projects](https://wcrp-cmip.org/mips/) such as [CMIP6](../datasets/climate_projection_data/CMIP6.ipynb), a model may be run under different greenhouse gas [emissions scenarios](./Emissions_scenarios.html) and even multiple times with different initial conditions. This generates a large number of distinct, yet comparable simulations of climate evolution. Instead of determining one of these outcomes to be a best result or estimate, each is considered one plausible possibility, scattered around the actual but uncertain future yet to develop. The uncertainties involved in this process include the emissions scenario uncertainty, structural model uncertainty and natural internal climate variability. They are best represented by employing ensembles of these simulations.

Emissions scenario uncertainty is related to the assumptions made for future GHG emissions from human activity and is discussed in this [section](./Emissions_scenarios.html).

Structural model uncertainty arises from the limitations and approximations made in climate models to represent processes. Climate models, while based on physical principles of fluid dynamics and thermodynamics, parameterize many processes at scales smaller than their spatial resolution, such as cloud formation or thunderstorms. This means that these small-scale processes are represented by simplified approximations rather than resolved explicitly by the physics of the model. Different climate modelling groups use different parameterizations and model structures, leading to different responses to the same external forcings, such as greenhouse gas concentrations. The diversity among models adds to the uncertainty in climate ensembles but is beneficial for capturing the range of possible outcomes.

The third important source of uncertainty, natural climate variability, refers to the chaotic nature of the climate system, and leads to different sequences of weather events even under the same external forcings. Natural climate variability can be studied either by running a model over very long timescales or by running multiple member simulations of the same model. Such member simulations consist of the exact same experiment setup, exept for a small perturbation of the intial conditions. A perturbation may be a different starting date or the exchange of an input layer, such as using the slightly different soil moisture from an earlier time step. The resulting simulations will be constrained by the same boundary conditions, including the GHG scenario, but due to the perturbations the simulations will quickly diverge, leading to different sequences of events in the members. Single model initial-condition large ensembles (SMILEs) are ensembles of many member simulations used for the study of climate variability and extreme events (see the [CanLEAD dataset](../datasets/climate_projection_data/CanLEAD.ipynb)).

It may be tempting to determine a "best performing model" for a climate assessment. However, such attempts are considered bad practice, primarily because a single model or simulation will not cover any of the inherent climate simulation uncertainty. Furthermore, a model performing well with respect to a selected metric, may be outperformed on another metric by a different model. Good practice for climate assessment uses ensembles of climate simulations to enhance robustness and reliability through the combination of outputs of multiple climate models. This allows to factor in uncertainty from model structure and to account for the climate system's natural variability in climate analysis for the electricity sector. [Emissions scenarios](./Emissions_scenarios.html) uncertainty must also be considered when building an ensemble for climate impact assessment.

ClimateData.ca has an [illustrated explanation of the rationale of using multi-model ensembles](https://climatedata.ca/resource/multi-model-ensembles/) and Ouranos provides an [overview of different types of climate simulation ensembles](https://www.ouranos.ca/en/understanding-climate-concepts/climate-simulations).

### Ensemble Size Reduction

Climate simulation ensembles composed from different models, emissions scenarios and members consist of many, and often over 100 simulations. This exceeds the capacities of evaluation for many users, often related to running impact models driven by climate simulation data. Several techniques have been developed to reduce the number of ensemble members while largely preserving the full ensemble characteristics. @Lutz2016 propose a systematic approach to an envelope-based model selection. @Casajus2016 apply k-means cluster analysis to identify a representative subset of simulations from an ensemble based on multiple user-defined criteria. @Cannon2015, in contrast, propose a method to construct ordered sub-samples of simulations that systematically span the ensemble spread using multi-criteria selection. Using multiple hydroclimatological indicators, @Braun2021 compare the uncertainty captured by a reduced ensemble when compared to the initial ensemble. The [xclim library](https://xclim.readthedocs.io/en/stable/index.html)'s section on [ensemble reduction](https://xclim.readthedocs.io/en/stable/api.html#ensemble-reduction) povides Python code for the k-means clustering approach (@Casajus2016) and the KKZ method (@Cannon2015).


