---
title: "Climate Vulnerability and Risk Assessments"
bibliography: adaptation.bib 
editor: 
  markdown: 
    wrap: 72
---

Climate vulnerability and risk assessments are tools for understanding
how climate change may impact electricity sector activities. These types
of analysis can be scaled to meet the needs of the sector activity. They
could be conducted in a very limited way for an individual component or
could be expanded to an entire generating station, transmission corridor
or other asset classes.

For a vulnerability and risk assessment to be most successful it should
be integrating into existing processes. For example, the assessment
could be conducted as part of a dam safety review or as part of a
planning exercise of a new transmission line. The overall process will
be very similar.

## Existing Standards and Guides

These various codes and standards are produced by standards
organizations such as the International Standards Organization (ISO) or
the Canadian Standards Assocation (CSA), government agencies such as
Environment and Climate Change Canada (ECCC) or the Canadian Nuclear
Safety Commissions (CNSC) as well as industry groups such as the
Electric Power Research Institute (EPRI) or the Canadian Dam Association
(CDA). In some cases climate data is explicitly included in the
standard, which has already been extracted by climate experts. In other
cases they outline a process which must be followed to understand
climate risks and vulnerabilities.

There are many guidance documents and standards that exist for
conducting climate vulnerability and risk assessments. Each has their
own uses, strengths and weaknesses. For the purposes of this guidance
several existing guides and standards have been referenced capturing the
best elements of each and filling in gaps where they were identified.

In almost all cases the available documents are about the process of
climate risk and vulnerability assessments and few provide concrete
guidance on the use of climate data in that process, unless they have
been explicitly included in data tables for calculation.

| Type                                       | Document                                                                                                                                              | Notes                                                 | Reference  |
|:-------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------|------------|
|General|International Organization for Standardization (ISO) 14091: Adaptation to Climate Change -- Guidelines on vulnerability, impacts and risk assessment|Internationally recognized framework|(@ISO14091)|
|Hydroelectric|Canadian Standards Association (CSA) S9101.1: Climate change vulnerability assessments for dams in Canada|Aligns with Canadian Dam Association (CDA) processes|(@CSAS910)|
|Nuclear|Electric Power Research Institute (EPRI) 3002023814: Climate vulnerability assessment guidance for Nuclear Power Plants|Specific for nuclear power industry|(@epri_n)|
|General|Environment and Climate Change Canada ECCC SACC-CCR: Strategic assessment of climate change: Assessing climate change resilience|For projects subject to Impact Assessments|(@sacc)|                                                       |            |
|General|Electric Power Research Institute (EPRI) 3002029124: Climate READi asset vulnerability assessments: Considerations and resources|Framework for energy sector|(@readi)|

: Reference Climate Risk and Vulnerability Guidance

A generic framework for conducting a climate change risk assessment is
shown below. Following the scope and purpose of this guide the greatest
detail will focus on the use of climate data and therefore the actual
elements of vulnerability and risk assessments. The previously mentioned
guidance documents are good sources of information for sector specific
guidance on framing and assessment and undersanding a system.

```{mermaid}
%%| fig-align: center
%%| fig-cap: "Generic Workflow for Adaptation"
---
config:
    flowchart:
        curve: linear
---
flowchart-elk TD
    A[Step 1: Develop Scope]:::basic --> B[Step 2: Understand System]:::basic
    B --> C[Step 3: Hazard & Exposure Assessment]:::basic
    C --> D[Step 4: Vulnerability Assessment]:::basic
    H[Step 7: Institutionalize Decision]:::basic
    D --> |No Vulnerability| H
    D --> |Vulnerable| E[Step 5: Risk Assessment]:::basic
    F[Step 6: Adaptation Plan]:::basic
    D & E --- J1[ ]:::join
    J1 --> |Unacceptable Vulnerability or Risk| F
    E --> |Risk Acceptable| H
    F --> H

    classDef basic fill:#CAD4D6
    classDef focus fill:#CAD4D6, stroke:#CE153D, color:#CE153D
    classDef join height:0px
```

::: {#doctip .callout-tip collapse="true" title="Transparency & Documentation"}
Clear and transparent documentation of a vulnerability and risk
assessment is important. The whole process should be documented well
enough that it could be easily repeated by an independent group and
either come to the same conclusions or clearly understand how
conclusions were drawn. This should include any assumptions (implicit
and explicit), rationale for choices made and conclusions reached.
:::

## References

::: {#refs}
:::
